[runtime]
output_dir = "runs"
log_file = "log.jsonl"
summary_csv = "summary.csv"
max_file_size_mb = 25
convert_timeout_s = 100
enable_local_api = false
parallelism = 1

[runtime.limits]
max_pages = 500
max_slides = 500
max_sheets = 50

[runtime.batch]
default_parallelism = 1
single_run_default = false

[runtime.jobs]
worker_pool_size = 0
retention_days = 7
dedupe_enabled = false
keep_partials = false

[formats]
allowed = [
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  "application/pdf",
  "text/html",
  "text/plain",
  "message/rfc822",
]

[api]
host = "127.0.0.1"
port = 8000
